version: '3.1'

secrets:
  MONGO_USER:
    external: true
  MONGO_PASSWORD:
    external: true
  MONGO_ROOT_USER:
    external: true
  MONGO_ROOT_PASSWORD:
    external: true
  MONGO_HOST:
    external: true
  HCAPTCHA_SECRET:
    external: true
  JWTPrivateKey:
    external: true
  JWTPublicKey:
    external: true
  GRAFANA_USER:
    external: true
  GRAFANA_PASSWORD:
    external: true

services:
  wwts_website:
    image: ghcr.io/leotuet/ui-we-want-to-sleep:prod
    container_name: wwts_website
    restart: unless-stopped

  wwts_api:
    image: ghcr.io/leotuet/backend-we-want-to-sleep:prod
    container_name: wwts_api
    environment:
      - NODE_ENV=production
      - PORT=3000
    secrets:
      - MONGO_USER
      - MONGO_PASSWORD
      - HCAPTCHA_SECRET
      - JWTPrivateKey
      - JWTPublicKey
      - MONGO_HOST
    restart: unless-stopped

  wwts_nginx:
    image: macbre/nginx-brotli:latest
    container_name: wwts_nginx
    volumes:
      - /etc/letsencrypt:/etc/letsencrypt
      - /usr/share/nginx/html:/usr/share/nginx/html
      - ./nginx.conf:/etc/nginx/nginx.conf
    deploy:
      mode: global
      placement:
        constraints:
          - node.role == manager
    ports:
      - "80:80"
      - "443:443"
  wwts_db:
    image: mongo
    container_name: wwts_db
    environment:
      MONGO_INITDB_ROOT_PASSWORD_FILE: /run/secrets/MONGO_ROOT_PASSWORD
      MONGO_INITDB_ROOT_USERNAME_FILE: /run/secrets/MONGO_ROOT_USER
      MONGO_INITDB_DATABASE: admin
      MONGO_DATABASE: wwts
      MONGO_USERNAME_FILE: /run/secrets/MONGO_USER
      MONGO_PASSWORD_FILE: /run/secrets/MONGO_PASSWORD
    volumes:
      - ./data/mongo-volume/wwts:/data/db
      - ./init-mongo.sh:/docker-entrypoint-initdb.d/init-mongo.sh
    secrets:
      - MONGO_USER
      - MONGO_PASSWORD
      - MONGO_ROOT_USER
      - MONGO_ROOT_PASSWORD
    restart: unless-stopped
  wwts_grafana:
    image: grafana/grafana:6.7.2
    container_name: wwts_grafana
    volumes:
      - grafana_data:/var/lib/grafana
      - ./grafana/provisioning:/etc/grafana/provisioning
    environment:
      GF_SECURITY_ADMIN_USER: /run/secrets/GRAFANA_USER
      GF_SECURITY_ADMIN_PASSWORD: /run/secrets/GRAFANA_PASSWORD
      GF_USERS_ALLOW_SIGN_UP: false
    secrets:
      - GRAFANA_USER
      - GRAFANA_PASSWORD
    restart: unless-stopped
    expose:
      - 3000
    labels:
      org.label-schema.group: "monitoring"   
